services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tandem-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tandemdb
      POSTGRES_USER: tandem
      POSTGRES_PASSWORD: tandem_dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tandem-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tandem -d tandemdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Optional - Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tandem-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - tandem-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  tandem-network:
    driver: bridge

