import { CreateCardTemplateDTO } from '@core/models/Card';
import { CardCategory, TaskFrequency } from '@shared/types';

/**
 * Simplified Fair Play card deck
 * 36 essential household responsibility cards organized by category
 */
export const CARD_TEMPLATES: CreateCardTemplateDTO[] = [
  // HOME CARE (10 cards)
  {
    name: 'Daily Tidying',
    category: CardCategory.HOME_CARE,
    description: 'Keep common areas clean and organized on a daily basis',
    conceptionDescription: 'Decide what "tidy" means and which areas need daily attention',
    planningDescription: 'Create a routine for tidying and determine best timing',
    executionDescription: 'Physically tidy spaces, put things away, wipe surfaces',
    frequency: TaskFrequency.DAILY,
    iconName: 'home',
  },
  {
    name: 'Laundry',
    category: CardCategory.HOME_CARE,
    description: 'Manage the complete laundry process from dirty to clean and put away',
    conceptionDescription: 'Decide when laundry needs to be done and sorting system',
    planningDescription: 'Sort clothes, check for stains, gather supplies',
    executionDescription: 'Wash, dry, fold, and put away all laundry',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'shirt',
  },
  {
    name: 'Dishes & Kitchen Cleanup',
    category: CardCategory.HOME_CARE,
    description: 'Keep kitchen clean including dishes, counters, and appliances',
    conceptionDescription: 'Decide on dish washing schedule and cleanliness standards',
    planningDescription: 'Empty dishwasher, organize dirty dishes',
    executionDescription: 'Wash/load dishes, wipe counters, clean sink and appliances',
    frequency: TaskFrequency.DAILY,
    iconName: 'utensils',
  },
  {
    name: 'Deep Cleaning',
    category: CardCategory.HOME_CARE,
    description: 'Thorough cleaning of bathrooms, floors, and deep-clean tasks',
    conceptionDescription: 'Determine which areas need deep cleaning and frequency',
    planningDescription: 'Schedule cleaning sessions, gather supplies',
    executionDescription: 'Scrub, vacuum, mop, dust all areas thoroughly',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'sparkles',
  },
  {
    name: 'Trash & Recycling',
    category: CardCategory.HOME_CARE,
    description: 'Empty trash, manage recycling, and handle waste disposal',
    conceptionDescription: 'Know trash schedule and what goes where',
    planningDescription: 'Monitor trash levels, prepare bins for pickup',
    executionDescription: 'Empty bins, take to curb, bring bins back in',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'trash',
  },
  {
    name: 'Home Maintenance',
    category: CardCategory.HOME_CARE,
    description: 'Track and complete home repairs and maintenance tasks',
    conceptionDescription: 'Notice what needs fixing or maintaining',
    planningDescription: 'Schedule repairs, find contractors, order parts',
    executionDescription: 'Complete fixes or coordinate with professionals',
    frequency: TaskFrequency.AS_NEEDED,
    iconName: 'wrench',
  },
  {
    name: 'Yard Work',
    category: CardCategory.HOME_CARE,
    description: 'Maintain outdoor spaces including lawn, garden, and yard',
    conceptionDescription: 'Decide on yard care standards and seasonal needs',
    planningDescription: 'Schedule mowing, plan seasonal tasks',
    executionDescription: 'Mow, trim, weed, rake, and maintain outdoor spaces',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'tree',
  },
  {
    name: 'Home Organization',
    category: CardCategory.HOME_CARE,
    description: 'Declutter and organize household spaces and storage',
    conceptionDescription: 'Identify areas that need organization systems',
    planningDescription: 'Plan storage solutions, gather organizing supplies',
    executionDescription: 'Sort, purge, organize, and maintain systems',
    frequency: TaskFrequency.SEASONAL,
    iconName: 'package',
  },
  {
    name: 'Pet Care',
    category: CardCategory.HOME_CARE,
    description: 'Feed, exercise, and care for household pets',
    conceptionDescription: 'Understand pet needs and care schedule',
    planningDescription: 'Track vet appointments, order supplies',
    executionDescription: 'Feed, walk, play with, and care for pets daily',
    frequency: TaskFrequency.DAILY,
    iconName: 'dog',
  },
  {
    name: 'Car Care',
    category: CardCategory.HOME_CARE,
    description: 'Maintain vehicles including cleaning and maintenance',
    conceptionDescription: 'Know maintenance schedule and car care needs',
    planningDescription: 'Schedule service, track registrations',
    executionDescription: 'Clean car, handle maintenance and repairs',
    frequency: TaskFrequency.MONTHLY,
    iconName: 'car',
  },

  // FOOD & MEALS (8 cards)
  {
    name: 'Meal Planning',
    category: CardCategory.FOOD_MEALS,
    description: 'Decide what meals to prepare for the week',
    conceptionDescription: 'Consider schedules, preferences, and dietary needs',
    planningDescription: 'Choose recipes, check pantry, plan balanced meals',
    executionDescription: 'Finalize meal plan and communicate to household',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'calendar',
  },
  {
    name: 'Grocery Shopping',
    category: CardCategory.FOOD_MEALS,
    description: 'Purchase all food and household supplies',
    conceptionDescription: 'Know what items are needed and where to shop',
    planningDescription: 'Create shopping list, plan store trip',
    executionDescription: 'Shop, transport, and put away all groceries',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'shopping-cart',
  },
  {
    name: 'Breakfast',
    category: CardCategory.FOOD_MEALS,
    description: 'Prepare and serve breakfast daily',
    conceptionDescription: 'Decide what breakfast options work for family',
    planningDescription: 'Ensure breakfast supplies are available',
    executionDescription: 'Prepare, serve, and clean up breakfast',
    frequency: TaskFrequency.DAILY,
    iconName: 'coffee',
  },
  {
    name: 'Lunch',
    category: CardCategory.FOOD_MEALS,
    description: 'Prepare lunch including school/work lunches',
    conceptionDescription: 'Plan lunch types and packing system',
    planningDescription: 'Prep ingredients, ensure containers are ready',
    executionDescription: 'Make and pack lunches, clean up',
    frequency: TaskFrequency.DAILY,
    iconName: 'sandwich',
  },
  {
    name: 'Dinner',
    category: CardCategory.FOOD_MEALS,
    description: 'Prepare and serve dinner',
    conceptionDescription: 'Decide what to cook and timing',
    planningDescription: 'Prep ingredients, start cooking at right time',
    executionDescription: 'Cook, serve, and coordinate dinner',
    frequency: TaskFrequency.DAILY,
    iconName: 'utensils',
  },
  {
    name: 'Snacks & Beverages',
    category: CardCategory.FOOD_MEALS,
    description: 'Keep snacks and drinks stocked and accessible',
    conceptionDescription: 'Know family snack preferences and needs',
    planningDescription: 'Monitor inventory, add to shopping list',
    executionDescription: 'Stock, organize, and prepare snacks',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'apple',
  },
  {
    name: 'Special Dietary Needs',
    category: CardCategory.FOOD_MEALS,
    description: 'Manage allergies, restrictions, and special diets',
    conceptionDescription: 'Understand dietary requirements',
    planningDescription: 'Find suitable recipes and products',
    executionDescription: 'Ensure safe, appropriate food is available',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'shield',
  },
  {
    name: 'Kitchen Inventory',
    category: CardCategory.FOOD_MEALS,
    description: 'Track pantry staples and prevent food waste',
    conceptionDescription: 'Know what staples to keep on hand',
    planningDescription: 'Check expiration dates, organize pantry',
    executionDescription: 'Update inventory, use food before it expires',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'list',
  },

  // CHILDCARE (6 cards - applicable if household has kids)
  {
    name: 'Morning Routine',
    category: CardCategory.CHILDCARE,
    description: 'Get kids up, dressed, fed, and ready for day',
    conceptionDescription: 'Create morning routine that works',
    planningDescription: 'Prepare clothes and supplies the night before',
    executionDescription: 'Wake kids, help with routine, get them out door',
    frequency: TaskFrequency.DAILY,
    iconName: 'sun',
  },
  {
    name: 'Bedtime Routine',
    category: CardCategory.CHILDCARE,
    description: 'Complete evening routine and get kids to bed',
    conceptionDescription: 'Establish consistent bedtime routine',
    planningDescription: 'Start routine at consistent time',
    executionDescription: 'Bath, pajamas, teeth, stories, tuck in',
    frequency: TaskFrequency.DAILY,
    iconName: 'moon',
  },
  {
    name: 'School Communication',
    category: CardCategory.CHILDCARE,
    description: 'Manage school emails, forms, and teacher communication',
    conceptionDescription: 'Stay on top of school requirements',
    planningDescription: 'Check school communications daily',
    executionDescription: 'Respond to emails, sign forms, coordinate',
    frequency: TaskFrequency.DAILY,
    iconName: 'school',
  },
  {
    name: 'Homework Help',
    category: CardCategory.CHILDCARE,
    description: 'Support children with homework and projects',
    conceptionDescription: 'Know what support kids need',
    planningDescription: 'Create homework time and space',
    executionDescription: 'Help with assignments, check completed work',
    frequency: TaskFrequency.DAILY,
    iconName: 'book',
  },
  {
    name: 'Kid Activities & Sports',
    category: CardCategory.CHILDCARE,
    description: 'Manage extracurricular activities and transportation',
    conceptionDescription: 'Decide on activities and commitments',
    planningDescription: 'Track schedules, register, pay fees',
    executionDescription: 'Transport to activities, coordinate with coaches',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'ball',
  },
  {
    name: 'Kid Medical & Health',
    category: CardCategory.CHILDCARE,
    description: 'Manage children\'s healthcare and appointments',
    conceptionDescription: 'Know medical needs and provider info',
    planningDescription: 'Schedule checkups, track vaccinations',
    executionDescription: 'Take to appointments, manage medications',
    frequency: TaskFrequency.AS_NEEDED,
    iconName: 'heart',
  },

  // FINANCIAL (4 cards)
  {
    name: 'Bill Payment',
    category: CardCategory.FINANCIAL,
    description: 'Pay all household bills on time',
    conceptionDescription: 'Know all bills and due dates',
    planningDescription: 'Track due dates, ensure funds available',
    executionDescription: 'Pay bills, track payments, file documents',
    frequency: TaskFrequency.MONTHLY,
    iconName: 'dollar-sign',
  },
  {
    name: 'Budget Management',
    category: CardCategory.FINANCIAL,
    description: 'Track spending and manage household budget',
    conceptionDescription: 'Create budget categories and limits',
    planningDescription: 'Review spending patterns monthly',
    executionDescription: 'Track expenses, adjust budget as needed',
    frequency: TaskFrequency.MONTHLY,
    iconName: 'pie-chart',
  },
  {
    name: 'Taxes & Legal',
    category: CardCategory.FINANCIAL,
    description: 'Handle tax preparation and legal documents',
    conceptionDescription: 'Understand tax obligations and deadlines',
    planningDescription: 'Gather documents, schedule with accountant',
    executionDescription: 'Complete tax returns, file documents',
    frequency: TaskFrequency.SEASONAL,
    iconName: 'file-text',
  },
  {
    name: 'Insurance Management',
    category: CardCategory.FINANCIAL,
    description: 'Manage all household insurance policies',
    conceptionDescription: 'Know what coverage is needed',
    planningDescription: 'Review policies annually, compare rates',
    executionDescription: 'Maintain policies, handle claims',
    frequency: TaskFrequency.SEASONAL,
    iconName: 'shield',
  },

  // SOCIAL & FAMILY (4 cards)
  {
    name: 'Gift Giving',
    category: CardCategory.SOCIAL_FAMILY,
    description: 'Remember occasions and handle gift buying',
    conceptionDescription: 'Track birthdays, holidays, and occasions',
    planningDescription: 'Shop for gifts in advance',
    executionDescription: 'Buy, wrap, and deliver gifts on time',
    frequency: TaskFrequency.AS_NEEDED,
    iconName: 'gift',
  },
  {
    name: 'Social Planning',
    category: CardCategory.SOCIAL_FAMILY,
    description: 'Coordinate social events and gatherings',
    conceptionDescription: 'Decide what social events to host or attend',
    planningDescription: 'Schedule events, send invitations',
    executionDescription: 'Prepare for and execute events',
    frequency: TaskFrequency.MONTHLY,
    iconName: 'users',
  },
  {
    name: 'Family Relationships',
    category: CardCategory.SOCIAL_FAMILY,
    description: 'Maintain connections with extended family',
    conceptionDescription: 'Decide how often to connect with family',
    planningDescription: 'Schedule calls, visits, celebrations',
    executionDescription: 'Make calls, send updates, coordinate visits',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'heart',
  },
  {
    name: 'Photo & Memory Keeping',
    category: CardCategory.SOCIAL_FAMILY,
    description: 'Capture and organize family photos and memories',
    conceptionDescription: 'Decide how to document family life',
    planningDescription: 'Take photos regularly, organize digitally',
    executionDescription: 'Create albums, back up photos, share with family',
    frequency: TaskFrequency.MONTHLY,
    iconName: 'camera',
  },

  // PERSONAL CARE (4 cards)
  {
    name: 'Personal Health Appointments',
    category: CardCategory.PERSONAL_CARE,
    description: 'Manage your own healthcare and appointments',
    conceptionDescription: 'Know what preventive care you need',
    planningDescription: 'Schedule annual checkups and appointments',
    executionDescription: 'Attend appointments, follow medical advice',
    frequency: TaskFrequency.SEASONAL,
    iconName: 'heart-pulse',
  },
  {
    name: 'Self-Care Time',
    category: CardCategory.PERSONAL_CARE,
    description: 'Schedule and protect personal wellness time',
    conceptionDescription: 'Identify what self-care means for you',
    planningDescription: 'Block time on calendar, arrange coverage',
    executionDescription: 'Take your self-care time without guilt',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'spa',
  },
  {
    name: 'Wardrobe Management',
    category: CardCategory.PERSONAL_CARE,
    description: 'Maintain and organize clothing for yourself',
    conceptionDescription: 'Know what you need and what fits',
    planningDescription: 'Seasonal wardrobe swaps, identify needs',
    executionDescription: 'Shop, repair, donate, organize clothing',
    frequency: TaskFrequency.SEASONAL,
    iconName: 'shirt',
  },
  {
    name: 'Personal Development',
    category: CardCategory.PERSONAL_CARE,
    description: 'Invest in your own growth and learning',
    conceptionDescription: 'Identify areas for personal growth',
    planningDescription: 'Find resources, courses, or communities',
    executionDescription: 'Dedicate time to learning and development',
    frequency: TaskFrequency.WEEKLY,
    iconName: 'book-open',
  },
];

