declare const tokens: {
  primary: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
  };
  secondary: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
  };
  cranberry: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
  };
  evergreen: {
    50: string;
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
  };
  error: { 50: string; 100: string; 200: string; 500: string; 600: string; 700: string };
  surface: { DEFAULT: string; muted: string; dim: string; hover: string };
  border: { DEFAULT: string; light: string; muted: string; strong: string };
  cream: string;
  warm: { border: string; label: string };
  sherbet: {
    mint: { fill: string; line: string; title: string; sub: string };
    peach: { fill: string; line: string; title: string; sub: string };
    lilac: { fill: string; line: string; title: string; sub: string };
    butter: { fill: string; line: string; title: string; sub: string };
    blush: { fill: string; line: string; title: string; sub: string };
    coral: { fill: string; line: string; title: string; sub: string };
  };
  accent: { catch: string; action: string; claim: string };
  text: { DEFAULT: string; secondary: string; muted: string; light: string };
  success: { 50: string; 100: string; 600: string; 700: string };
  warning: { 50: string; 100: string; 500: string; 600: string; 700: string; 800: string };
  neutral: { 500: string };
  info: { 100: string; 700: string };
};
export = tokens;
